### ISSUE TITLE
Rework the set()-oriented configuration tree

### ISSUE THREAD

**Issue by CyrilBrulebois** [PiRogueToolSuite/pirogue-admin#3]
Hi @TontonSancho,

Spotted while having a look around, and seeing the `FIXME` about the `set()` to (sorted) list conversion: I'm not sure why it's important to work on sets, do you have specific needs in mind that would require working with sets instead of lists?

I don't have any examples right now, but it seems possible we could have something like this for some actions:

1. do something with a
1. run command
1. do something with b
1. run command

in which case we would lose the “run command” multiplicity *and* the ordering.

We're already losing the order in various places, e.g.:

```
    actions:
    - /usr/local/sbin/reconfigure-pirogue-flow-inspector
    - chmod +x /usr/local/sbin/reconfigure-pirogue-flow-inspector
```

or:

```
    actions:
    - ip6tables-restore /etc/iptables/rules.v6
    - iptables-restore /etc/iptables/rules.v4
    - systemctl daemon-reload
    - systemctl enable dnsmasq
    - systemctl enable hostapd
    - systemctl restart dnsmasq
    - systemctl restart hostapd
    - systemctl restart systemd-sysctl
    - systemctl try-restart nftables
    - systemctl unmask dnsmasq
```

(Granted, the first one is only a couple hours old, the second one was there already.)

**Comment by TontonSancho** [comment]
Hi @CyrilBrulebois .

Keep in mind [the context](https://github.com/PiRogueToolSuite/pirogue-admin/blob/302448c52816d93b82c9af2061dbb0fe49e8e669/pirogue_admin/package_config/__init__.py#L361C9-L361C31) of this `FIXME` : the purpose of this function is to get a 'relation map' between notions, not to have an 'execution plan'. This needs uniqueness.
Using `set()` to collect such a 'relation graph' is the *quick and dirty way* to ensure the uniqueness for the expected result.

[The `FIXME` note](https://github.com/PiRogueToolSuite/pirogue-admin/blob/302448c52816d93b82c9af2061dbb0fe49e8e669/pirogue_admin/package_config/__init__.py#L424-L427) is only there to keep a track of a future needed 'refactor' of the following (ugly) triple loop : I'm pretty sure yaml dumper have a cleaner way to not spit out ugly `!!set` meta class data (what's is already explained in the comment).

The 'good' order and multiplicity of internal `actions` lists are normally kept (leave untouched) accessing `configs.files.actions`. 
Not sure what the worry here : Are you saying a call to the `get_configuration_tree` function changes internal integrity of the lists ?
If no, what are you suggesting ?

**Comment by CyrilBrulebois** [comment]
I had the context in mind but it didn't make it clear it's only about “relation map between notions” aspect…
